#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-nexus-public
Version  : 2.7.2.01
Release  : 1
URL      : https://repo1.maven.org/maven2/org/sonatype/nexus/nexus-client-core/2.7.2-01/nexus-client-core-2.7.2-01.jar
Source0  : https://repo1.maven.org/maven2/org/sonatype/nexus/nexus-client-core/2.7.2-01/nexus-client-core-2.7.2-01.jar
Source1  : https://repo1.maven.org/maven2/org/sonatype/nexus/nexus-client-core/2.7.2-01/nexus-client-core-2.7.2-01.pom
Source2  : https://repo1.maven.org/maven2/org/sonatype/nexus/nexus-components/2.7.2-01/nexus-components-2.7.2-01.pom
Source3  : https://repo1.maven.org/maven2/org/sonatype/nexus/nexus-oss/2.7.2-01/nexus-oss-2.7.2-01.pom
Source4  : https://repo1.maven.org/maven2/org/sonatype/nexus/plugins/nexus-plugins-restlet1x/2.7.2-01/nexus-plugins-restlet1x-2.7.2-01.pom
Source5  : https://repo1.maven.org/maven2/org/sonatype/nexus/plugins/nexus-plugins/2.7.2-01/nexus-plugins-2.7.2-01.pom
Source6  : https://repo1.maven.org/maven2/org/sonatype/nexus/plugins/nexus-restlet1x-model/2.7.2-01/nexus-restlet1x-model-2.7.2-01.jar
Source7  : https://repo1.maven.org/maven2/org/sonatype/nexus/plugins/nexus-restlet1x-model/2.7.2-01/nexus-restlet1x-model-2.7.2-01.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : EPL-1.0
Requires: mvn-nexus-public-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-nexus-public package.
Group: Data

%description data
data components for the mvn-nexus-public package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/nexus/nexus-client-core/2.7.2-01
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/nexus/nexus-client-core/2.7.2-01

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/nexus/nexus-client-core/2.7.2-01
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/nexus/nexus-client-core/2.7.2-01

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/nexus/nexus-components/2.7.2-01
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/nexus/nexus-components/2.7.2-01

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/nexus/nexus-oss/2.7.2-01
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/nexus/nexus-oss/2.7.2-01

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/nexus/plugins/nexus-plugins-restlet1x/2.7.2-01
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/nexus/plugins/nexus-plugins-restlet1x/2.7.2-01

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/nexus/plugins/nexus-plugins/2.7.2-01
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/nexus/plugins/nexus-plugins/2.7.2-01

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/nexus/plugins/nexus-restlet1x-model/2.7.2-01
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/nexus/plugins/nexus-restlet1x-model/2.7.2-01

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/nexus/plugins/nexus-restlet1x-model/2.7.2-01
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/nexus/plugins/nexus-restlet1x-model/2.7.2-01


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/sonatype/nexus/nexus-client-core/2.7.2-01/nexus-client-core-2.7.2-01.jar
/usr/share/java/.m2/repository/org/sonatype/nexus/nexus-client-core/2.7.2-01/nexus-client-core-2.7.2-01.pom
/usr/share/java/.m2/repository/org/sonatype/nexus/nexus-components/2.7.2-01/nexus-components-2.7.2-01.pom
/usr/share/java/.m2/repository/org/sonatype/nexus/nexus-oss/2.7.2-01/nexus-oss-2.7.2-01.pom
/usr/share/java/.m2/repository/org/sonatype/nexus/plugins/nexus-plugins-restlet1x/2.7.2-01/nexus-plugins-restlet1x-2.7.2-01.pom
/usr/share/java/.m2/repository/org/sonatype/nexus/plugins/nexus-plugins/2.7.2-01/nexus-plugins-2.7.2-01.pom
/usr/share/java/.m2/repository/org/sonatype/nexus/plugins/nexus-restlet1x-model/2.7.2-01/nexus-restlet1x-model-2.7.2-01.jar
/usr/share/java/.m2/repository/org/sonatype/nexus/plugins/nexus-restlet1x-model/2.7.2-01/nexus-restlet1x-model-2.7.2-01.pom
